/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitap;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryo
 */

public class baithuchanh3 extends javax.swing.JFrame {
    DefaultListModel model11;
    DefaultListModel model12;
    public baithuchanh3() {
        initComponents();
        model11=new DefaultListModel();
        model11.addElement("Bóng Đá");
        model11.addElement("Bóng Chuyền");
        model11.addElement("Cầu Lông");
        model11.addElement("Bơi Lội");
        model12=new DefaultListModel();
        listtrai.setModel(model11);
        listphai.setModel(model12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listphai = new javax.swing.JList<>();
        btquaphai = new javax.swing.JButton();
        btquaphaihet = new javax.swing.JButton();
        btquatraihet = new javax.swing.JButton();
        btcong = new javax.swing.JButton();
        btquatrai = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listtrai = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton5.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listphai);

        btquaphai.setText(">");
        btquaphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquaphaiActionPerformed(evt);
            }
        });

        btquaphaihet.setText(">>");
        btquaphaihet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquaphaihetActionPerformed(evt);
            }
        });

        btquatraihet.setText("<<");
        btquatraihet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquatraihetActionPerformed(evt);
            }
        });

        btcong.setText("+");
        btcong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcongActionPerformed(evt);
            }
        });

        btquatrai.setText("<");
        btquatrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquatraiActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(listtrai);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Danh Sách môn thể thao");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Môn yêu thích");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btquaphai)
                    .addComponent(btquaphaihet)
                    .addComponent(btquatrai)
                    .addComponent(btquatraihet))
                .addGap(105, 105, 105)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(btcong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btquaphai)
                        .addGap(28, 28, 28)
                        .addComponent(btquaphaihet)
                        .addGap(18, 18, 18)
                        .addComponent(btquatrai)
                        .addGap(27, 27, 27)
                        .addComponent(btquatraihet))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addGap(18, 18, 18)
                .addComponent(btcong)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcongActionPerformed
        String sTheThao=JOptionPane.showInputDialog(this,"Nhap mon the thao");
        model11.addElement(sTheThao);
    }//GEN-LAST:event_btcongActionPerformed

    private void btquaphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquaphaiActionPerformed
        // TODO add your handling code here:
        int[] indexs = listtrai.getSelectedIndices();
        for(int i = indexs.length-1; i>=0;i--)
        {
            model12.addElement(model11.get(indexs[i]));
            model11.remove(indexs[i]);
        }
    }//GEN-LAST:event_btquaphaiActionPerformed

    private void btquatraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquatraiActionPerformed
        // TODO add your handling code here:
        int[] indexs = listphai.getSelectedIndices();
        for(int i = indexs.length-1; i>=0;i--)
        {
            model11.addElement(model12.get(indexs[i]));
            model12.remove(indexs[i]);
        }
    }//GEN-LAST:event_btquatraiActionPerformed

    private void btquaphaihetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquaphaihetActionPerformed
        // TODO add your handling code here:
        int rt = model11.getSize();
        for(int i = 0; i < rt ; i++)
        {
            model12.addElement(model11.get(i));
        }
        model11.clear();
    }//GEN-LAST:event_btquaphaihetActionPerformed

    private void btquatraihetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquatraihetActionPerformed
        // TODO add your handling code here:
        int rp = model12.getSize();
        for(int i = 0; i < rp ; i++)
        {
            model11.addElement(model12.get(i));
        }
        model12.clear();
    }//GEN-LAST:event_btquatraihetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baithuchanh3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baithuchanh3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baithuchanh3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baithuchanh3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baithuchanh3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcong;
    private javax.swing.JButton btquaphai;
    private javax.swing.JButton btquaphaihet;
    private javax.swing.JButton btquatrai;
    private javax.swing.JButton btquatraihet;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listphai;
    private javax.swing.JList<String> listtrai;
    // End of variables declaration//GEN-END:variables
}
